---
driver:
  name: vagrant

provisioner:
  name: shell

platforms:
  - name: bionic64-ptfe
    driver:
      box: <username>/<box>
      provider: virtualbox
      box_check_update: true

verifier:
  name: inspec

suites:
  - name: default

